# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-10-27 15:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('special_admin', '0011_auto_20161024_1730'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='tag',
            field=models.CharField(max_length=50),
        ),
    ]
