# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-10-22 14:51
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('special_admin', '0006_auto_20161022_1447'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='courses',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='special_admin.Course'),
        ),
    ]
