# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-10-24 16:09
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('special_admin', '0008_auto_20161023_1514'),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.CharField(max_length=20)),
                ('detail', models.CharField(max_length=100)),
                ('deadline', models.CharField(max_length=20)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='special_admin.Course')),
            ],
        ),
    ]
