# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-10-24 16:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('special_admin', '0009_task'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='detail',
            field=models.CharField(max_length=400),
        ),
    ]
