# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-10-24 17:30
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('special_admin', '0010_auto_20161024_1647'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='course',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='special_admin.Course'),
        ),
    ]
