# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-10-29 11:31
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('special_admin', '0013_feedbackform'),
    ]

    operations = [
        migrations.RenameField(
            model_name='feedbackform',
            old_name='questions',
            new_name='question_set',
        ),
    ]
